import { Inter } from "next/font/google";
import "./globals.css";
import SiteLayout from "./ui/layout/SiteLayout";
import AuthProvider from "./contexts/AuthProvider";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <SiteLayout>{children}</SiteLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
